export const PUBLICATIONS_FETCH = 'PUBLICATIONS_FETCH'
export const PUBLICATIONS_LOADING = 'PUBLICATIONS_LOADING'
export const PUBLICATIONS_ERROR = 'PUBLICATIONS_ERROR'
export const PUBLICATIONS_BY_USER = 'PUBLICATIONS_BY_USER'